# Generated by Django 5.2.17 on 2026-09-24 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('application_tier', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('testing_weight', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('source_code_weight', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('pass_threshold', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('warning_threshold', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('status', models.CharField(default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'db_table': 'project_versions',
            },
        ),
    ]
