# Generated by Django 5.2.17 on 2026-09-28 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0002_alter_artifact_storage_key'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCodeResultModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('code_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hard_gate_triggered', models.BooleanField(default=False)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artifacts.artifact')),
                ('project_version', models.ForeignKey(db_column='project_version_id', on_delete=django.db.models.deletion.CASCADE, to='projects.projectversion')),
            ],
            options={
                'db_table': 'source_code_results',
            },
        ),
    ]
