# Generated by Django 5.2.17 on 2026-09-24 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('testing_weight_snapshot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source_code_weight_snapshot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pass_threshold_snapshot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('warning_threshold_snapshot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('project_version', models.ForeignKey(db_column='project_version_id', on_delete=django.db.models.deletion.CASCADE, to='projects.projectversion')),
            ],
            options={
                'db_table': 'analysis_runs',
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('testing_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source_code_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('decision', models.CharField(blank=True, max_length=50, null=True)),
                ('findings', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(db_column='analysis_run_id', on_delete=django.db.models.deletion.CASCADE, to='gate_engine.analysisrun')),
            ],
            options={
                'db_table': 'analysis_results',
            },
        ),
    ]
