# Generated by Django 5.2.17 on 2026-09-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='storage_key',
            field=models.CharField(max_length=500),
        ),
    ]
